### ISSUE TITLE
Fix the status of the wireless runstop

### ISSUE THREAD

**Issue by Rayman** [tue-robotics/dashboard#8]
If the physical runstop is pressed, the wireless runstop state is unknown (tue-robotics/amigo_hardware#2). Make the button grey out.

## TODO
- [x] listen to the ebutton topic: `/amigo/ebutton_status`
- [x] implement ebutton timeout 24606d7726a02baa2349ac077e950fa206dfa4d5

**Comment by Rayman** [comment]
```yaml
---
header: 
  seq: 588
  stamp: 
    secs: 0
    nsecs: 0
  frame_id: ''
status: 
  - 
    level: 0
    name: Wired
    message: ''
    hardware_id: ''
    values: []
  - 
    level: 1
    name: Wireless
    message: ''
    hardware_id: ''
    values: []
---
```
